!!binary |
  YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IHByb21ldGhl
  dXMtY29uZmlnCiAgbmFtZXNwYWNlOiBtb25pdG9yaW5nCmRhdGE6CiAgcHJvbWV0aGV1cy55bWw6
  IHwKICAgIGdsb2JhbDoKICAgICAgc2NyYXBlX2ludGVydmFsOiA1cwogICAgICBldmFsdWF0aW9u
  X2ludGVydmFsOiA1cwogICAgcnVsZV9maWxlczoKICAgICAgLSAvZXRjL3Byb21ldGhldXMvcHJv
  bWV0aGV1cy5ydWxlcwogICAgYWxlcnRpbmc6CiAgICAgIGFsZXJ0bWFuYWdlcnM6CiAgICAgIC0g
  c2NoZW1lOiBodHRwCiAgICAgICAgc3RhdGljX2NvbmZpZ3M6CiAgICAgICAgLSB0YXJnZXRzOgog
  ICAgICAgICAgLSAiYWxlcnRtYW5hZ2VyLm1vbml0b3Jpbmcuc3ZjOjkwOTMiCiAgICBzY3JhcGVf
  Y29uZmlnczoKICAgICAgLSBqb2JfbmFtZTogJ2t1YmVybmV0ZXMtYXBpc2VydmVycycKICAgICAg
  ICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgICAgICAgLSByb2xlOiBlbmRwb2ludHMKICAgICAg
  ICBzY2hlbWU6IGh0dHBzCiAgICAgICAgdGxzX2NvbmZpZzoKICAgICAgICAgIGNhX2ZpbGU6IC92
  YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jYS5jcnQKICAgICAg
  ICBiZWFyZXJfdG9rZW5fZmlsZTogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZp
  Y2VhY2NvdW50L3Rva2VuCiAgICAgICAgcmVsYWJlbF9jb25maWdzOgogICAgICAgIC0gc291cmNl
  X2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25hbWVzcGFjZSwgX19tZXRhX2t1YmVybmV0ZXNf
  c2VydmljZV9uYW1lLCBfX21ldGFfa3ViZXJuZXRlc19lbmRwb2ludF9wb3J0X25hbWVdCiAgICAg
  ICAgICBhY3Rpb246IGtlZXAKICAgICAgICAgIHJlZ2V4OiBkZWZhdWx0O2t1YmVybmV0ZXM7aHR0
  cHMKICAgICAgLSBqb2JfbmFtZTogJ2t1YmVybmV0ZXMtbm9kZXMnCiAgICAgICAgc2NoZW1lOiBo
  dHRwcwogICAgICAgIHRsc19jb25maWc6CiAgICAgICAgICBjYV9maWxlOiAvdmFyL3J1bi9zZWNy
  ZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvY2EuY3J0CiAgICAgICAgYmVhcmVyX3Rv
  a2VuX2ZpbGU6IC92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC90
  b2tlbgogICAgICAgIGt1YmVybmV0ZXNfc2RfY29uZmlnczoKICAgICAgICAtIHJvbGU6IG5vZGUK
  ICAgICAgICByZWxhYmVsX2NvbmZpZ3M6CiAgICAgICAgLSBhY3Rpb246IGxhYmVsbWFwCiAgICAg
  ICAgICByZWdleDogX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9sYWJlbF8oLispCiAgICAgICAgLSB0
  YXJnZXRfbGFiZWw6IF9fYWRkcmVzc19fCiAgICAgICAgICByZXBsYWNlbWVudDoga3ViZXJuZXRl
  cy5kZWZhdWx0LnN2Yzo0NDMKICAgICAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJu
  ZXRlc19ub2RlX25hbWVdCiAgICAgICAgICByZWdleDogKC4rKQogICAgICAgICAgdGFyZ2V0X2xh
  YmVsOiBfX21ldHJpY3NfcGF0aF9fCiAgICAgICAgICByZXBsYWNlbWVudDogL2FwaS92MS9ub2Rl
  cy8kezF9L3Byb3h5L21ldHJpY3MKICAgICAgCiAgICAgIC0gam9iX25hbWU6ICdrdWJlcm5ldGVz
  LXBvZHMnCiAgICAgICAga3ViZXJuZXRlc19zZF9jb25maWdzOgogICAgICAgIC0gcm9sZTogcG9k
  CiAgICAgICAgcmVsYWJlbF9jb25maWdzOgogICAgICAgIC0gc291cmNlX2xhYmVsczogW19fbWV0
  YV9rdWJlcm5ldGVzX3BvZF9hbm5vdGF0aW9uX3Byb21ldGhldXNfaW9fc2NyYXBlXQogICAgICAg
  ICAgYWN0aW9uOiBrZWVwCiAgICAgICAgICByZWdleDogdHJ1ZQogICAgICAgIC0gc291cmNlX2xh
  YmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9hbm5vdGF0aW9uX3Byb21ldGhldXNfaW9fcGF0
  aF0KICAgICAgICAgIGFjdGlvbjogcmVwbGFjZQogICAgICAgICAgdGFyZ2V0X2xhYmVsOiBfX21l
  dHJpY3NfcGF0aF9fCiAgICAgICAgICByZWdleDogKC4rKQogICAgICAgIC0gc291cmNlX2xhYmVs
  czogW19fYWRkcmVzc19fLCBfX21ldGFfa3ViZXJuZXRlc19wb2RfYW5ub3RhdGlvbl9wcm9tZXRo
  ZXVzX2lvX3BvcnRdCiAgICAgICAgICBhY3Rpb246IHJlcGxhY2UKICAgICAgICAgIHJlZ2V4OiAo
  W146XSspKD86OlxkKyk/OyhcZCspCiAgICAgICAgICByZXBsYWNlbWVudDogJDE6JDIKICAgICAg
  ICAgIHRhcmdldF9sYWJlbDogX19hZGRyZXNzX18KICAgICAgICAtIGFjdGlvbjogbGFiZWxtYXAK
  ICAgICAgICAgIHJlZ2V4OiBfX21ldGFfa3ViZXJuZXRlc19wb2RfbGFiZWxfKC4rKQogICAgICAg
  IC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25hbWVzcGFjZV0KICAgICAgICAg
  IGFjdGlvbjogcmVwbGFjZQogICAgICAgICAgdGFyZ2V0X2xhYmVsOiBrdWJlcm5ldGVzX25hbWVz
  cGFjZQogICAgICAgIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9uYW1l
  XQogICAgICAgICAgYWN0aW9uOiByZXBsYWNlCiAgICAgICAgICB0YXJnZXRfbGFiZWw6IGt1YmVy
  bmV0ZXNfcG9kX25hbWUKICAgICAgCiAgICAgIC0gam9iX25hbWU6ICdrdWJlLXN0YXRlLW1ldHJp
  Y3MnCiAgICAgICAgc3RhdGljX2NvbmZpZ3M6CiAgICAgICAgICAtIHRhcmdldHM6IFsna3ViZS1z
  dGF0ZS1tZXRyaWNzLmt1YmUtc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAnXQogICAgICAt
  IGpvYl9uYW1lOiAna3ViZXJuZXRlcy1jYWR2aXNvcicKICAgICAgICBzY2hlbWU6IGh0dHBzCiAg
  ICAgICAgdGxzX2NvbmZpZzoKICAgICAgICAgIGNhX2ZpbGU6IC92YXIvcnVuL3NlY3JldHMva3Vi
  ZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jYS5jcnQKICAgICAgICBiZWFyZXJfdG9rZW5fZmls
  ZTogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3Rva2VuCiAg
  ICAgICAga3ViZXJuZXRlc19zZF9jb25maWdzOgogICAgICAgIC0gcm9sZTogbm9kZQogICAgICAg
  IHJlbGFiZWxfY29uZmlnczoKICAgICAgICAtIGFjdGlvbjogbGFiZWxtYXAKICAgICAgICAgIHJl
  Z2V4OiBfX21ldGFfa3ViZXJuZXRlc19ub2RlX2xhYmVsXyguKykKICAgICAgICAtIHRhcmdldF9s
  YWJlbDogX19hZGRyZXNzX18KICAgICAgICAgIHJlcGxhY2VtZW50OiBrdWJlcm5ldGVzLmRlZmF1
  bHQuc3ZjOjQ0MwogICAgICAgIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25v
  ZGVfbmFtZV0KICAgICAgICAgIHJlZ2V4OiAoLispCiAgICAgICAgICB0YXJnZXRfbGFiZWw6IF9f
  bWV0cmljc19wYXRoX18KICAgICAgICAgIHJlcGxhY2VtZW50OiAvYXBpL3YxL25vZGVzLyR7MX0v
  cHJveHkvbWV0cmljcy9jYWR2aXNvcgogICAgICAKICAgICAgLSBqb2JfbmFtZTogJ2t1YmVybmV0
  ZXMtc2VydmljZS1lbmRwb2ludHMnCiAgICAgICAga3ViZXJuZXRlc19zZF9jb25maWdzOgogICAg
  ICAgIC0gcm9sZTogZW5kcG9pbnRzCiAgICAgICAgcmVsYWJlbF9jb25maWdzOgogICAgICAgIC0g
  c291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfYW5ub3RhdGlvbl9wcm9t
  ZXRoZXVzX2lvX3NjcmFwZV0KICAgICAgICAgIGFjdGlvbjoga2VlcAogICAgICAgICAgcmVnZXg6
  IHRydWUKICAgICAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNl
  X2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19zY2hlbWVdCiAgICAgICAgICBhY3Rpb246IHJlcGxh
  Y2UKICAgICAgICAgIHRhcmdldF9sYWJlbDogX19zY2hlbWVfXwogICAgICAgICAgcmVnZXg6ICho
  dHRwcz8pCiAgICAgICAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2Vydmlj
  ZV9hbm5vdGF0aW9uX3Byb21ldGhldXNfaW9fcGF0aF0KICAgICAgICAgIGFjdGlvbjogcmVwbGFj
  ZQogICAgICAgICAgdGFyZ2V0X2xhYmVsOiBfX21ldHJpY3NfcGF0aF9fCiAgICAgICAgICByZWdl
  eDogKC4rKQogICAgICAgIC0gc291cmNlX2xhYmVsczogW19fYWRkcmVzc19fLCBfX21ldGFfa3Vi
  ZXJuZXRlc19zZXJ2aWNlX2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19wb3J0XQogICAgICAgICAg
  YWN0aW9uOiByZXBsYWNlCiAgICAgICAgICB0YXJnZXRfbGFiZWw6IF9fYWRkcmVzc19fCiAgICAg
  ICAgICByZWdleDogKFteOl0rKSg/OjpcZCspPzsoXGQrKQogICAgICAgICAgcmVwbGFjZW1lbnQ6
  ICQxOiQyCiAgICAgICAgLSBhY3Rpb246IGxhYmVsbWFwCiAgICAgICAgICByZWdleDogX19tZXRh
  X2t1YmVybmV0ZXNfc2VydmljZV9sYWJlbF8oLispCiAgICAgICAgLSBzb3VyY2VfbGFiZWxzOiBb
  X19tZXRhX2t1YmVybmV0ZXNfbmFtZXNwYWNlXQogICAgICAgICAgYWN0aW9uOiByZXBsYWNlCiAg
  ICAgICAgICB0YXJnZXRfbGFiZWw6IGt1YmVybmV0ZXNfbmFtZXNwYWNlCiAgICAgICAgLSBzb3Vy
  Y2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9uYW1lXQogICAgICAgICAgYWN0
  aW9uOiByZXBsYWNlCiAgICAgICAgICB0YXJnZXRfbGFiZWw6IGt1YmVybmV0ZXNfbmFtZQogICAg
  ICAtIGpvYl9uYW1lOiAnbm9kZS1leHBvcnRlcicKICAgICAgICBrdWJlcm5ldGVzX3NkX2NvbmZp
  Z3M6CiAgICAgICAgICAtIHJvbGU6IGVuZHBvaW50cwogICAgICAgIHJlbGFiZWxfY29uZmlnczoK
  ICAgICAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19lbmRwb2ludHNfbmFt
  ZV0KICAgICAgICAgIHJlZ2V4OiAnbm9kZS1leHBvcnRlcicKICAgICAgICAgIGFjdGlvbjoga2Vl
  cAogICAgICAtIGpvYl9uYW1lOiBwb3N0Z3JlcwogICAgICAgIHN0YXRpY19jb25maWdzOgogICAg
  ICAgIC0gdGFyZ2V0czogWydxc3ItZGItbWV0cmljcy5yb3RmOjkxODcnXQogICAgICAtIGpvYl9u
  YW1lOiBxc3ItYXBpCiAgICAgICAgc3RhdGljX2NvbmZpZ3M6CiAgICAgICAgLSB0YXJnZXRzOiBb
  J3Fzci1hcGktc2VydmljZS5yb3RmOjgwMDAnXQogICAgICAtIGpvYl9uYW1lOiBwb3MKICAgICAg
  ICBzdGF0aWNfY29uZmlnczoKICAgICAgICAtIHRhcmdldHM6IFsncG9zLW1ldHJpY3MucG9zOjkx
  MTMnXQotLS0KYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQpraW5kOiBD
  bHVzdGVyUm9sZQptZXRhZGF0YToKICBuYW1lOiBwcm9tZXRoZXVzCnJ1bGVzOgotIGFwaUdyb3Vw
  czogWyIiXQogIHJlc291cmNlczoKICAtIG5vZGVzCiAgLSBub2Rlcy9wcm94eQogIC0gc2Vydmlj
  ZXMKICAtIGVuZHBvaW50cwogIC0gcG9kcwogIHZlcmJzOiBbImdldCIsICJsaXN0IiwgIndhdGNo
  Il0KLSBhcGlHcm91cHM6CiAgLSBleHRlbnNpb25zCiAgcmVzb3VyY2VzOgogIC0gaW5ncmVzc2Vz
  CiAgdmVyYnM6IFsiZ2V0IiwgImxpc3QiLCAid2F0Y2giXQotIG5vblJlc291cmNlVVJMczogWyIv
  bWV0cmljcyJdCiAgdmVyYnM6IFsiZ2V0Il0KLS0tCmFwaVZlcnNpb246IHJiYWMuYXV0aG9yaXph
  dGlvbi5rOHMuaW8vdjEKa2luZDogQ2x1c3RlclJvbGVCaW5kaW5nCm1ldGFkYXRhOgogIG5hbWU6
  IHByb21ldGhldXMKcm9sZVJlZjoKICBhcGlHcm91cDogcmJhYy5hdXRob3JpemF0aW9uLms4cy5p
  bwogIGtpbmQ6IENsdXN0ZXJSb2xlCiAgbmFtZTogcHJvbWV0aGV1cwpzdWJqZWN0czoKLSBraW5k
  OiBTZXJ2aWNlQWNjb3VudAogIG5hbWU6IGRlZmF1bHQKICBuYW1lc3BhY2U6IG1vbml0b3Jpbmc=
