!!binary |
  YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IGdyYWZhbmEt
  ZGF0YXNvdXJjZXMKICBuYW1lc3BhY2U6IG1vbml0b3JpbmcKZGF0YToKICBwcm9tZXRoZXVzLnlh
  bWw6IHwtCiAgICB7CiAgICAgICAgImFwaVZlcnNpb24iOiAxLAogICAgICAgICJkYXRhc291cmNl
  cyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiYWNjZXNzIjoicHJveHkiLAogICAg
  ICAgICAgICAgICAgImVkaXRhYmxlIjogdHJ1ZSwKICAgICAgICAgICAgICAgICJuYW1lIjogInBy
  b21ldGhldXMiLAogICAgICAgICAgICAgICAgIm9yZ0lkIjogMSwKICAgICAgICAgICAgICAgICJ0
  eXBlIjogInByb21ldGhldXMiLAogICAgICAgICAgICAgICAgInVybCI6ICJodHRwOi8vcHJvbWV0
  aGV1cy1zZXJ2aWNlLm1vbml0b3Jpbmc6ODA4MCIsCiAgICAgICAgICAgICAgICAidmVyc2lvbiI6
  IDEKICAgICAgICAgICAgfQogICAgICAgIF0KICAgIH0=
