!!binary |
  YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IHJvdGYtZGIK
  ICBuYW1lc3BhY2U6IHJvdGYKZGF0YToKICBEQl9IT1NUOiAncXNyLWRiJwogIERCX1VTRVI6ICdh
  ZG1pbicKICBEQl9QV0Q6ICdhZG1pbicKICBEQl9OQU1FOiAncm90ZicKICBEQVRBX1NPVVJDRV9O
  QU1FOiAicG9zdGdyZXNxbDovL2FkbWluOmFkbWluQDEyNy4wLjAuMTo1NDMyL3JvdGY/c3NsbW9k
  ZT1kaXNhYmxlIg==
