apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    canary: '100'
    continent: australia
    loc: australia-southeast2
    mesh_id: proj-439133013195
  name: abm-australia-southeast2
